### ISSUE TITLE
pip install pysummarization does not work

### ISSUE THREAD

**Issue by Spandan-Madan** [chimera0/accel-brain-code#1]
pip installation fails with the error:-

Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/vp/1jfcmynj25d2d_3dpxr3yckr0000gn/T/pip-install-tqd95hyf/mecab-python3/

**Comment by chimera0** [comment]
I don't have enough information about that.
The only thing I can do is guess.

> Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/vp/1jfcmynj25d2d_3dpxr3yckr0000gn/T/pip-install-tqd95hyf/mecab-python3/

This library depends on [mecab-python3](https://pypi.org/project/mecab-python3/), which is python wrapper for mecab.

For instance, **if you use Ubuntu**, as you may have noticed,
the following error occurrs while building wheel for `mecab-python3`. 

> error: command 'gcc' failed with exit status 1

This problem can be solved with the following command:

```bash
apt-get install build-essential
pip install pysummarization
```

If you have not installed `mecab`, you can install with the following command:

```bash
apt-get install build-essential
apt-get install libmecab2 libmecab-dev mecab mecab-ipadic mecab-ipadic-utf8 mecab-utils
pip install pysummarization
```

# My environment

```bash
python -V
Python 3.6.5 :: Anaconda, Inc.
```

## Source

- ubuntu-1604-xenial-v20180814(Google Compute Engine)
