### ISSUE TITLE
pygan true_sampler

### ISSUE THREAD

**Issue by andrealbh** [chimera0/accel-brain-code#11]
I tried to create a true sampler object from the existing numerical datasets via ConditionalTrueSampler but the error message said Can't instantiate abstract class ConditionalTrueSampler with abstract methods add_condition, draw. How can I create the true sample using my own data?

**Comment by chimera0** [comment]
You just have to implement a subclass of the abstract class `ConditionalTrueSampler ` yourself. Only you know the distribution of the dataset you want to sample.

**Comment by andrealbh** [comment]
Thank you for your reply. I am a bit confused. I thought SinWaveTrueSampler generated a true sinwave dataset. But if I have already the true dataset, no need to generate more, how to implement the truesampler with existing true datasets? As I find the truesampler is needed for GAN train.

**Comment by accel-brain** [comment]
I don't think it has anything to do with this case, but this library has been extensively updated in the last 10 days, so please reinstall it just in case.

**Comment by accel-brain** [comment]
By the way, this model is not a model for *predicting* the true distribution. I suppose this model fundamentally does not meet your needs.
