### ISSUE TITLE
Gan_composer error

### ISSUE THREAD

**Issue by mpuig03** [chimera0/accel-brain-code#12]
I was trying to work this out, and an error raised when the function gan_composer.learn is called, as if it wasn't recognised. I think i made sura that everything that needs to be installed or run is working, but it still doesn't work. If anyone could give me some help :)

![image](https://user-images.githubusercontent.com/67662270/86393572-8c6c0c00-bc9d-11ea-87b5-7e0c559a6e0c.png)

**Comment by accel-brain** [comment]
Isn't the class not initialized?

I don't think it has anything to do with this case, but this library has been extensively updated in the last 10 days, so please reinstall it just in case.
