### ISSUE TITLE
How to change the number of sentences in the output summary by pysummarization?

### ISSUE THREAD

**Issue by smita181298** [chimera0/accel-brain-code#13]
I tried to evaluate pysummarization on the cnn dataset and observed that it always gives 10 sentences in the summary when the number of sentences in input text was varying from 20 to 100. How can I change the number of sentences in the output summary? Where do I need to make changes in the code?

**Comment by accel-brain** [comment]
What class did you use?

**Comment by smita181298** [comment]
Got it in TopRankAbstractor class where __top_n = 10 which can be changed.
