### ISSUE TITLE
how to get N number of sentences ?

### ISSUE THREAD

**Issue by JVK1987** [chimera0/accel-brain-code#14]
Hi Team,

am using the pysummarization technique to summarize my document. with this library am able to get the top 10 ranked sentences only. if i need more then 10 ?

And how this 10 sentences this technique is picking also i am not clear on the document.

please help on these two things.

**Comment by accel-brain** [comment]
#13

[#references](https://github.com/accel-brain/accel-brain-code/tree/master/Automatic-Summarization#references)

**Comment by JVK1987** [comment]
Hi Team,

thank you for your replay.

i am little confused that, is pysummarization is abstractive or extractive summarization method.

thanks in advance

**Comment by accel-brain** [comment]
In old natural language processing terms, this library basically performs an extraction (at least when you look at the functional output).

**Comment by JVK1987** [comment]
Ok, so you mean this method is Extractive text summarization.

to understand more about this pysummarization method easily. can you share any link how the top 10 sentences its picking.

**Comment by chimera0** [comment]
https://github.com/accel-brain/accel-brain-code/issues/14#issuecomment-661823566

**Comment by chimera0** [comment]
This issue seems to be a duplicate of #15 .

**Comment by accel-brain** [comment]
I’ll close this chat.
