### ISSUE TITLE
about bar_gram.py function extract_features

### ISSUE THREAD

**Issue by Maggie-Jing** [chimera0/accel-brain-code#17]
def extract_features(self, df):
        pitch_tuple = tuple(df.pitch.values.tolist())
        arr = np.zeros(self.__dim)
        try:
            arr[self.pitch_tuple_list.index(pitch_tuple)] = 1
        except ValueError:
            pitch_key = np.random.randint(low=0, high=len(pitch_tuple))
            arr[pitch_tuple[pitch_key]] = 1

        arr = arr.astype(float)
        return arr

If this exception is thrown, this line 'arr[pitch_tuple[pitch_key]] = 1' very likely go wrong, 'pitch_tuple[pitch_key] ' usually some big number. or you mean :
```
    except ValueError:
        pitch_key = np.random.randint(low=0, high=len(self.pitch_tuple_list))
        arr[pitch_key] = 1
```

**Comment by accel-brain** [comment]
I am sorry that my reply was delayed because of summer vacation.

I fixed the bug you mentioned here.
Please update the library to the latest version.

https://github.com/accel-brain/accel-brain-code/commit/643d848badeb0f597ee88ea919c3f4972b55b96a
