### ISSUE TITLE
Save the 'generative_model' to local file and load it to compose

### ISSUE THREAD

**Issue by Maggie-Jing** [chimera0/accel-brain-code#18]
Could you add a method to save the training model of 'gan_composer'? save to json or some format else, so that I can use 'gan_composer.compose()' quickly generate the appropriate MIDI. Or could you teach me how to save the 'generative_model' and load it from local file?

**Comment by accel-brain** [comment]
It is a reasonable issue, but it can be done with the current interface specifications based on mxnet.

If you want to save the parameters, execute the method as follows.

```python
gan_composer.generative_model.model.save_parameters(filename="path/to/your.params")
```

If you want to read the parameters, execute the method as follows.

```python
import mxnet as mx
gan_composer.generative_model.model.load_parameters(filename="path/to/your.params", ctx=mx.gpu())
```

We shall implement wrapper methods one of these days.

See also ...

- https://mxnet.incubator.apache.org/versions/1.6/api/python/docs/api/gluon/hybrid_block.html#mxnet.gluon.HybridBlock.load_parameters

**Comment by Maggie-Jing** [comment]
Thank you for reply to my question!
