### ISSUE TITLE
Module not found in pybdm

### ISSUE THREAD

**Issue by Shulk7** [chimera0/accel-brain-code#2]
Hi ! I have problems with pydbm 1.4.4 using search_maze_by_deep_q_network.ipynb. The module pydbm.cnn.convolutional_neural_network isn't found. Indeed I only found a convolutional_neural_network.pyx in pydbm/cnn not the actual module.
Thanks in advance for your help

**Comment by chimera0** [comment]
Thanks for your question,
I'm not sure your environment, but you should install dependencies.

https://github.com/chimera0/accel-brain-code/tree/master/Reinforcement-Learning#installation
