### ISSUE TITLE
Having implementation issues

### ISSUE THREAD

**Issue by gpulkitg** [chimera0/accel-brain-code#23]
I am not sure if the model is working properly. Do you know what the excepted Frechet Inception Distance should be?

**Comment by accel-brain** [comment]
In our design concept, the function of metric is too specific. We do not think it as even the minimum required option.

If the FID metric is what you need and should be in any problem setting (eg data augmentation) you are encountering, maybe you should extend it yourself according to your problem setting.

As a general theory, metric functions are relatively variable in that they depend on problem settings, domains, and data distributions. We recognize that other deep architecture functions are easy to methodize and have a high degree of commonality. we prefer that the two functions are loosely coupled.

On the other hand, if we are only talking about metric functions, the FID metric is the current standard (of 2020-2021). Someone else may have implemented it. Or you might find useful information for you to implement yourself if you look for it.

If you know what software can be, please send a pull request If you like :-)

**Comment by gpulkitg** [comment]
Thanks for your response. I'll submit a pull request if I can get it working with some modifications.
