### ISSUE TITLE
This library doesn't work and is unuseable. Save your time. It's clearly never been tested or used by the developer as it cannot be imported into any environment. 

### ISSUE THREAD

**Issue by SarahPeterson2854** [chimera0/accel-brain-code#26]
pip install pygan
then try to import 
from pygan.gan_image_generator import GANImageGenerator

Now you have a combination of import versions of numpy/pandas and mxnet that are impossible to reach.

**Comment by accel-brain** [comment]
Read official documents.
This is not a school that teaches how to use external libraries.
