### ISSUE TITLE
cycle_len limitation

### ISSUE THREAD

**Issue by xing-w** [chimera0/accel-brain-code#3]
I'm using pydbm to working on a problem similar to Encoder/Decoder for Anomaly Detection(EncDec-AD). I found the cycle_len's maximum value is 50. Why is that? Is it because the TanhFunction's memory size is 50? I want to use 128 point sequences. Is there any way to change this value? Thanks.

**Comment by chimera0** [comment]
Hi, 

The parameter can be set to any value considering memory management in your environment.

```python
tanh_function = TanhFunction(memory_len=128)
```

There is no reason for the initial value of this field to be `50` but it is recommended to set the sequence length as short as possible by devising the modeling from the regularization point of view.
