### ISSUE TITLE
No module named 'pycomposer.conditional_gan_composer'

### ISSUE THREAD

**Issue by helloWorld20484096** [chimera0/accel-brain-code#5]
`from pycomposer.conditional_gan_composer import ConditionalGANComposer`

`---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-10-060c45a03f68> in <module>
----> 1 from pycomposer.conditional_gan_composer import ConditionalGANComposer

ModuleNotFoundError: No module named 'pycomposer.conditional_gan_composer'`

**Comment by 1085164753** [comment]
![Screenshot (22)](https://user-images.githubusercontent.com/8839677/58860464-bdff5600-86de-11e9-913b-20ef2138b68d.png)

**Comment by helloWorld20484096** [comment]
![Screenshot (23)](https://user-images.githubusercontent.com/8839677/58860568-fdc63d80-86de-11e9-867d-1b3b82402775.png)

**Comment by helloWorld20484096** [comment]
![Screenshot (24)](https://user-images.githubusercontent.com/8839677/58860713-51d12200-86df-11e9-86c0-d9c1b147e5ab.png)

**Comment by helloWorld20484096** [comment]
Somehow, I think there are many bugs in this repository

**Comment by chimera0** [comment]
I can not understand anything just by counting events that occurred, so I emphasized the meaning and analyzed the problem itself.

If there is no problem with the path you have specified, both issues (#4 and #5) are just setuptool issues, so I'll handle them later.
