### ISSUE TITLE
Pip Install pydbm doesn't work

### ISSUE THREAD

**Issue by xSachinBharadwajx** [chimera0/accel-brain-code#6]
C:\Users\J5XE>pip install pydbm --user
Collecting pydbm
  Using cached https://files.pythonhosted.org/packages/8c/9f/bdd224e5e0917aed64d0e166401d7868153dfaa84a2b03f5d026430b9e05/pydbm-1.4.8.tar.gz
Could not install packages due to an EnvironmentError: [Errno 22] Invalid argument: 'C:\\Users\\J5XE\\AppData\\Local\\Temp\\pip-install-3j8nvr54\\pydbm\\build/lib.linux-x86_64-3.6/*.cpython-36m-x86_64-linux-gnu.so'

**Comment by chimera0** [comment]
#4
