### ISSUE TITLE
About how to use Q-learning

### ISSUE THREAD

**Issue by 123toorc** [chimera0/accel-brain-code#9]
Hi, I'm a student working on a project that requires using Q-learning.  I want to know is there any material about the packet function interfaces? I didn't find some useful info in README file.

**Comment by chimera0** [comment]
I don't know what your project is, but `QLearning` is just an abstract class, so I think you should implement your own subclass according to the functional requirements and use cases determined in your project.

Quite simply, what can be useful in a design can only be determined by those who can clarify the level of abstraction and functionality.
